language: python
services:
  - docker
before_install:
  - docker pull docker.pkg.github.com/donchesworth/dask-quik/dask-quik-pytest:v1
script: pytest # run tests
after_success:
  - codecov # submit coverage
