language: python
services:
  - docker
before_install:
  - echo $GITHUB_PAT | docker login docker.pkg.github.com -u donchesworth --password-stdin
  - docker build --tag dask-quik-test:latest .
install:
  - skip
script:
  - docker run -it dask-quik-test:latest