name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: donchesworth/dask-quik-test:latest
      # - 
      #   name: Test with pytest
      #   run: docker run -it dask-quik-test:latest
      # - 
      #   name: Upload codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
      #     verbose: true