name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: ghcr login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: donchesworth/dask-quik-test:latest
      -
        name: Run container
        uses: ghcr.io/donchesworth/dask-quik-test:latest
      # -
      #   name: Run container
      #   uses: actions/dask-quik-test-action@v1
  # container_run:
  #   runs-on: ubuntu-latest
  #   container: donchesworth/dask-quik-test:latest
  #   steps:
  #     -
  #       name: Run container
  #       run: /opt/dq/entrypoint.sh
      # - 
      #   name: Run container
      #   uses: addnab/docker-run-action@v2
      #   with:
      #     image: donchesworth/dask-quik-test:latest
      #     run: /opt/dq/entrypoint.sh
      # - 
      #   name: Test with pytest
      #   run: docker run -it dask-quik-test:latest
      # - 
      #   name: Upload codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: false
      #     verbose: true